# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly
matrix:
  allow_failures:
    - julia: nightly
env:
  - PYTHON=""
before_script:
  - julia -e 'using Pkg; Pkg.clone("https://github.com/PieterjanRobbe/SimpleMultigrid.jl.git"); Pkg.clone("https://github.com/PieterjanRobbe/NotSoSimpleMultigrid.jl.git"); Pkg.clone("https://github.com/PieterjanRobbe/MultilevelEstimators.jl.git"); Pkg.clone("https://github.com/PieterjanRobbe/LognormalDiffusionProblems.jl.git");'
notifications:
  email: false
after_success:
  # push coverage results to Coveralls
  - julia -e 'using Pkg; cd(Pkg.dir("MultilevelEstimators")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg; cd(Pkg.dir("MultilevelEstimators")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
